"""add new column to todo table

Revision ID: 9620cffcfd2d
Revises: 81283ab3dc13
Create Date: 2024-07-11 13:56:27.541033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9620cffcfd2d'
down_revision: Union[str, None] = '81283ab3dc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todo', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'updated_at')
    op.drop_column('todo', 'created_at')
    # ### end Alembic commands ###
